[build]
  publish = "public"
  command = ""

# SPA fallback to your main HTML file (kept as scrum_board.html by default)
[[redirects]]
  from = "/"
  to   = "/scrum_board.html"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/scrum_board.html"
  status = 200

# Optional headers
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"